-- Standard compliance and assurance job templates.
--
-- `due_date_rule` is { month_offset, day } applied to the end of the period the
-- job covers: month_offset 1 / day 15 means "the 15th of the month following
-- the period end". Statutory deadlines differ by jurisdiction - these are
-- sensible defaults that a partner can edit in Settings → Templates without a
-- code change. `internal_lead_days` is how many days ahead of the statutory
-- date the firm targets internal sign-off.

INSERT INTO task_templates
  (id, name, service_line, task_type, description, default_priority, default_recurrence,
   budget_hours, checklist, due_date_rule, internal_lead_days, active, created_at, updated_at)
VALUES
  ('tpl_vat_monthly',
   'Monthly VAT Return',
   'tax_compliance',
   'vat_return',
   'Preparation and filing of the monthly value added tax return, including reconciliation of output and input tax to the accounting records.',
   'high', 'monthly', 4,
   '[{"label":"Obtain sales listing and confirm completeness to the general ledger","mandatory":true},
     {"label":"Obtain purchases listing and verify input tax claims are supported by valid invoices","mandatory":true},
     {"label":"Reconcile output tax per return to revenue in the accounting records","mandatory":true},
     {"label":"Review exempt, zero-rated and relief supplies for correct treatment","mandatory":false},
     {"label":"Compute net VAT payable or refundable","mandatory":true},
     {"label":"Prepare the return schedule and supporting working papers","mandatory":true},
     {"label":"Obtain client confirmation of the figures","mandatory":false},
     {"label":"File the return and retain the acknowledgement","mandatory":true}]',
   '{"month_offset":1,"day":30}', 5, 1, datetime('now'), datetime('now')),

  ('tpl_paye_monthly',
   'Monthly PAYE Return',
   'tax_compliance',
   'paye_return',
   'Preparation and filing of the monthly employer pay-as-you-earn return, reconciled to the payroll register.',
   'high', 'monthly', 3,
   '[{"label":"Obtain the approved payroll register for the period","mandatory":true},
     {"label":"Reconcile gross emoluments per payroll to the general ledger","mandatory":true},
     {"label":"Verify benefit-in-kind and allowance treatment","mandatory":false},
     {"label":"Recompute tax on a sample of employees across bands","mandatory":true},
     {"label":"Agree the total tax deducted to the payment schedule","mandatory":true},
     {"label":"File the return and retain the acknowledgement","mandatory":true}]',
   '{"month_offset":1,"day":15}', 4, 1, datetime('now'), datetime('now')),

  ('tpl_wht_monthly',
   'Monthly Withholding Tax Return',
   'tax_compliance',
   'withholding_tax',
   'Preparation and filing of the monthly withholding tax return, with review of vendor payments for correct withholding rates.',
   'normal', 'monthly', 3,
   '[{"label":"Extract vendor payments for the period from the ledger","mandatory":true},
     {"label":"Confirm the correct withholding rate for each payment category","mandatory":true},
     {"label":"Identify payments where withholding was omitted and quantify exposure","mandatory":true},
     {"label":"Prepare withholding certificates for vendors","mandatory":false},
     {"label":"Agree total withheld to the tax control account","mandatory":true},
     {"label":"File the return and retain the acknowledgement","mandatory":true}]',
   '{"month_offset":1,"day":15}', 4, 1, datetime('now'), datetime('now')),

  ('tpl_cit_instalment',
   'Quarterly Corporate Tax Instalment',
   'tax_compliance',
   'cit_instalment',
   'Computation and settlement of the quarterly provisional corporate income tax instalment based on the current year forecast.',
   'normal', 'quarterly', 4,
   '[{"label":"Obtain year-to-date management accounts and full-year forecast","mandatory":true},
     {"label":"Recompute estimated chargeable income for the year","mandatory":true},
     {"label":"Compare against the revenue authority assessment on file","mandatory":false},
     {"label":"Compute the instalment due and prepare the payment schedule","mandatory":true},
     {"label":"Advise the client of the amount and due date","mandatory":true}]',
   '{"month_offset":0,"day":30}', 7, 1, datetime('now'), datetime('now')),

  ('tpl_cit_annual',
   'Annual Corporate Income Tax Return',
   'tax_compliance',
   'cit_return',
   'Preparation and filing of the annual corporate income tax return, including the tax computation and capital allowance schedules.',
   'high', 'annual', 24,
   '[{"label":"Obtain signed audited financial statements for the period","mandatory":true},
     {"label":"Prepare the tax computation reconciling accounting profit to chargeable income","mandatory":true},
     {"label":"Prepare capital allowance schedules and agree opening balances to the prior year return","mandatory":true},
     {"label":"Review disallowable expenses and non-taxable income classifications","mandatory":true},
     {"label":"Compute and schedule loss relief carried forward","mandatory":false},
     {"label":"Agree instalments and withholding tax credits to receipts on file","mandatory":true},
     {"label":"Determine the final balance payable or refundable","mandatory":true},
     {"label":"Obtain client and director approval of the return","mandatory":true},
     {"label":"File the return and retain the acknowledgement","mandatory":true}]',
   '{"month_offset":4,"day":30}', 14, 1, datetime('now'), datetime('now')),

  ('tpl_transfer_pricing',
   'Annual Transfer Pricing Return and Documentation',
   'tax_compliance',
   'transfer_pricing',
   'Preparation of the annual transfer pricing return and supporting local file documentation for related party transactions.',
   'normal', 'annual', 32,
   '[{"label":"Map all related party transactions for the period","mandatory":true},
     {"label":"Confirm the transfer pricing method applied to each transaction category","mandatory":true},
     {"label":"Update the benchmarking analysis and comparables set","mandatory":true},
     {"label":"Update the local file narrative for changes in the value chain","mandatory":true},
     {"label":"Reconcile disclosed amounts to the audited financial statements","mandatory":true},
     {"label":"File the return and retain the acknowledgement","mandatory":true}]',
   '{"month_offset":4,"day":30}', 14, 1, datetime('now'), datetime('now')),

  ('tpl_statutory_audit',
   'Statutory Audit of Financial Statements',
   'audit_assurance',
   'statutory_audit',
   'Full statutory audit engagement from planning through to issue of the auditor report, performed under the applicable auditing standards.',
   'high', 'annual', 160,
   '[{"label":"Confirm engagement acceptance, independence and the signed engagement letter","mandatory":true},
     {"label":"Perform client and engagement risk assessment","mandatory":true},
     {"label":"Document understanding of the entity and its internal control environment","mandatory":true},
     {"label":"Determine materiality and performance materiality","mandatory":true},
     {"label":"Prepare and agree the audit plan and team allocation","mandatory":true},
     {"label":"Execute tests of controls and substantive procedures by cycle","mandatory":true},
     {"label":"Complete the going concern assessment","mandatory":true},
     {"label":"Obtain and evaluate management representations","mandatory":true},
     {"label":"Prepare the draft financial statements and disclosure checklist","mandatory":true},
     {"label":"Clear the engagement quality review file notes","mandatory":true},
     {"label":"Prepare the management letter on control deficiencies","mandatory":false},
     {"label":"Obtain the signed representation letter and issue the auditor report","mandatory":true}]',
   '{"month_offset":4,"day":30}', 21, 1, datetime('now'), datetime('now')),

  ('tpl_financial_statements',
   'Annual Financial Statements Preparation',
   'bookkeeping',
   'financial_statements',
   'Preparation of a full set of annual financial statements from the trial balance, with supporting schedules and disclosure notes.',
   'normal', 'annual', 40,
   '[{"label":"Obtain the final adjusted trial balance","mandatory":true},
     {"label":"Prepare lead schedules for each balance sheet caption","mandatory":true},
     {"label":"Post year-end accruals, prepayments and depreciation","mandatory":true},
     {"label":"Prepare the statement of financial position and statement of profit or loss","mandatory":true},
     {"label":"Prepare the statement of cash flows and changes in equity","mandatory":true},
     {"label":"Draft the disclosure notes and complete the disclosure checklist","mandatory":true},
     {"label":"Agree comparatives to the prior year signed statements","mandatory":true},
     {"label":"Circulate the draft to the client for approval","mandatory":true}]',
   '{"month_offset":3,"day":31}', 14, 1, datetime('now'), datetime('now')),

  ('tpl_management_accounts',
   'Monthly Management Accounts',
   'bookkeeping',
   'management_accounts',
   'Monthly close and preparation of management accounts with variance commentary for client management.',
   'normal', 'monthly', 8,
   '[{"label":"Confirm all bank accounts are reconciled for the period","mandatory":true},
     {"label":"Review and clear the suspense and unallocated accounts","mandatory":true},
     {"label":"Post recurring journals for accruals, prepayments and depreciation","mandatory":true},
     {"label":"Reconcile debtors and creditors control accounts to the sub-ledgers","mandatory":true},
     {"label":"Reconcile inventory to the latest count records","mandatory":false},
     {"label":"Prepare the management accounts pack","mandatory":true},
     {"label":"Prepare variance commentary against budget and prior period","mandatory":true}]',
   '{"month_offset":1,"day":10}', 3, 1, datetime('now'), datetime('now')),

  ('tpl_payroll_run',
   'Monthly Payroll Processing',
   'payroll',
   'payroll_run',
   'Monthly payroll computation, approval and disbursement support, including statutory deduction schedules.',
   'urgent', 'monthly', 5,
   '[{"label":"Obtain and validate the change log for joiners, leavers and rate changes","mandatory":true},
     {"label":"Process the payroll and review the exception report","mandatory":true},
     {"label":"Compute statutory deductions and employer contributions","mandatory":true},
     {"label":"Compare the payroll against the prior month and explain movements","mandatory":true},
     {"label":"Obtain client authorisation of the net pay schedule","mandatory":true},
     {"label":"Issue payslips and file the payroll register","mandatory":true},
     {"label":"Prepare the statutory remittance schedules","mandatory":true}]',
   '{"month_offset":0,"day":25}', 2, 1, datetime('now'), datetime('now')),

  ('tpl_annual_return',
   'Registrar Annual Return Filing',
   'company_secretarial',
   'annual_return',
   'Preparation and filing of the annual return with the companies registry, including confirmation of statutory particulars.',
   'normal', 'annual', 6,
   '[{"label":"Confirm the registered office and principal place of business","mandatory":true},
     {"label":"Confirm the current register of directors, secretary and auditors","mandatory":true},
     {"label":"Confirm the shareholding structure and any transfers in the period","mandatory":true},
     {"label":"Attach the audited financial statements where required","mandatory":true},
     {"label":"Obtain director signature on the return","mandatory":true},
     {"label":"File the return, pay the fee and retain the acknowledgement","mandatory":true}]',
   '{"month_offset":6,"day":30}', 21, 1, datetime('now'), datetime('now')),

  ('tpl_regulatory_return',
   'Periodic Regulatory Return',
   'regulatory_filing',
   'regulatory_return',
   'Preparation and submission of a periodic prudential or sector regulatory return to the relevant supervisory authority.',
   'high', 'quarterly', 12,
   '[{"label":"Confirm the applicable return template and reporting version in force","mandatory":true},
     {"label":"Extract and validate the source data for the reporting period","mandatory":true},
     {"label":"Complete the return schedules and internal validation checks","mandatory":true},
     {"label":"Reconcile key figures to the accounting records","mandatory":true},
     {"label":"Document the basis for any judgemental classifications","mandatory":false},
     {"label":"Obtain the required officer certification","mandatory":true},
     {"label":"Submit the return and retain the submission receipt","mandatory":true}]',
   '{"month_offset":1,"day":20}', 5, 1, datetime('now'), datetime('now')),

  ('tpl_tax_health_check',
   'Tax Health Check Review',
   'tax_advisory',
   'tax_health_check',
   'Diagnostic review of the client tax position across all tax heads to identify exposures and planning opportunities ahead of an audit.',
   'normal', 'none', 40,
   '[{"label":"Agree the scope, periods and tax heads with the client","mandatory":true},
     {"label":"Review corporate income tax filings and computations for the periods under review","mandatory":true},
     {"label":"Review indirect tax compliance and reconciliations","mandatory":true},
     {"label":"Review employment tax and withholding compliance","mandatory":true},
     {"label":"Quantify identified exposures with penalty and interest estimates","mandatory":true},
     {"label":"Identify available reliefs and planning opportunities","mandatory":false},
     {"label":"Prepare the findings report with prioritised recommendations","mandatory":true}]',
   NULL, 10, 1, datetime('now'), datetime('now')),

  ('tpl_client_onboarding',
   'Client Onboarding and Acceptance',
   'advisory',
   'onboarding',
   'New client acceptance procedures covering identity verification, conflict checks, risk rating and engagement documentation.',
   'high', 'none', 6,
   '[{"label":"Perform conflict of interest check across the existing client base","mandatory":true},
     {"label":"Complete customer due diligence and verify beneficial ownership","mandatory":true},
     {"label":"Screen the client and principals against sanctions and adverse media","mandatory":true},
     {"label":"Assign the client risk rating and document the rationale","mandatory":true},
     {"label":"Obtain partner approval of client acceptance","mandatory":true},
     {"label":"Issue the engagement letter and obtain countersignature","mandatory":true},
     {"label":"Set up the client, engagements and recurring jobs in the practice system","mandatory":true}]',
   NULL, 5, 1, datetime('now'), datetime('now'));
